import { NgModule } from '@angular/core';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  IonRouterOutlet,
  IonRouterLink,
  IonBackdrop,
  IonBadge,
  IonButton,
  IonCard,
  IonCheckbox,
  IonChip,
  IonContent,
  IonGrid,IonRow,IonCol,
  IonDatetime,
  IonFab,
  IonHeader,
  IonIcon,
  IonImg,
  IonInput,
  IonItem,
  IonLabel,
  IonList,
  IonLoading,
  IonMenu,
  IonPopover,
  IonProgressBar,
  IonRadio,
  IonRange,
  IonRefresher,
  IonReorder,
  IonSegment,
  IonSelect,
 
  IonSpinner,
  IonTabs,
  IonText,
  IonTextarea,
  IonToast,
  IonToolbar,
  IonActionSheet,
  IonAlert,
  IonModal,
  IonSelectOption,
  IonAccordion,
  IonTabBar,

} from '@ionic/angular/standalone';



//     IonApp: Root element for your Ionic application.

const ionicModules: any = [
  IonRouterOutlet,
  IonBackdrop,
  IonBadge,
  IonButton,
  IonCard,
  IonCheckbox,
  IonChip,
  IonSelectOption,
  IonSelect,
  IonContent,
  IonDatetime,
  IonFab,
  IonGrid,
  IonHeader,
  IonIcon,
  IonImg,
  IonInput,
  IonItem,
  IonLabel,
  IonList,
  IonLoading,
  IonMenu,
  IonPopover,
  IonProgressBar,
  IonRadio,
  IonRange,
  IonRefresher,
  IonReorder,
  IonSegment,
  IonSelect,
  // IonSlide,
  // IonSlides,
  IonSpinner,
  IonTabs,
  IonText,
  IonTextarea,
  IonToast,
  IonToolbar,
  IonActionSheet,
  IonAlert,
  IonModal,
  // IonRouter,
  // IonRoute,
  // IonRouterDirection,
  IonAccordion,
  IonBackdrop,
  IonRow,IonCol,
  // IonCalendar,
  // IonDatetimeCalendar,
  // IonDatetimePopover,
  // IonGridList,
  // IonMenuController,
  // IonModalController,
  // IonPickerController,
  // IonProgressBarPopover,
  // IonSlidesController,
  IonTabBar,
  // IonTabsController,
  // IonToastController,
  // IonVirtualScroll,
]

@NgModule({
  declarations: [],
  imports: [ionicModules],
  exports: [ionicModules],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class IonicModule { }




